version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"  # Host port:Container port
    environment:
      - NODE_ENV=development  # Development environment for backend
      - MONGO_URL=mongodb://mongo:27017/mydatabase
    volumes:
      - ./backend:/app  # Mount code for live dev changes
      - /app/node_modules  # Keeps node_modules persistent inside the container
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3001:3000"  # Expose React dev server on host port 3000
    environment:
      - CHOKIDAR_USEPOLLING=true  # Ensures file system polling in containers (necessary in some setups)
    volumes:
      - ./frontend:/app  # Mount code for live dev changes
      - /app/node_modules  # Keeps node_modules persistent inside the container
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"  # Expose MongoDB on host port 27017
    volumes:
      - mongo-data:/data/db  # Persistent MongoDB data

volumes:
  mongo-data:  # Named volume ensures data is stored persistently
